### PR TITLE
Check if  rpc servers have changed.

### PR DESCRIPTION
**Pull request by hidden1nin**
This adds a simple check to see if the servers changed from when the llmServer was first created.

### CODE REVIEW

**Comment by ecyht2** [comment]
Is this PR ready? I can't get it to build.

**Comment by hidden1nin** [comment]
Go is not one of my best languages, I believe the issue is with scoping (I'm not sure if GetAvailibleServers) is being used right. Overall the idea was to expand the data structure for LlmServer and add a list of servers when it was created, then compare it during NeedsReload(). I tried to implement this, but I am not super familiar with the codebase or GO. Hopefully this helps!

**Comment by hidden1nin** [comment]
I believe I had the data structure wrong using []string instead of 	servers map[string]string.

**Comment by ecyht2** [comment]
I still can't get it to build, but I managed to fix it already. Thanks for the help.

**Pull request closed without merging**
